### ISSUE TITLE
wsh hanged sometimes 

### ISSUE THREAD

**Issue by elianka** [cloudfoundry/warden#110]
I used wsh to attach to container and execute some shell scripts.
sometimes, the wsh was blocked and never returned. And the scripts had beed completed.
What's the reason?

the gdb info for wsh is attached. and i have read the code of wsh, it seems to be blocked in reading msg from wshd. So is there some issue on this?

![image](https://cloud.githubusercontent.com/assets/4158830/17238864/021feb32-5592-11e6-9573-8ff90019b60d.png)

**Comment by swetharepakula** [comment]
Hi @elianka,

We currently do now know of any issues, so we were hoping to get more information from you to better assess what could be going wrong.

How are you using wsh, as in what steps are you taking before you  get the hanging output?

Another thing we wanted to know is what you are hoping to use wsh for? We may be able to suggest other ways to accomplish your end goal.

Thanks,
@swetharepakula
RuntimeOG Team

**Comment by elianka** [comment]
hi @swetharepakula,
Thanks for your reply.
 as the question, I use wsh to attach to container and execute some shell scripts.
the container is running a postgresql database, and the shell scripts runned by wsh is to do some database actions, may last for a while.
sometimes, wsh will be hanged and without return.

**Comment by swetharepakula** [comment]
Hi @elianka,

We were more interested in the specific command line steps (scrubbed of all credentials and private information) you used to get to the hanging output. 

There is this [link](https://docs.cloudfoundry.org/running/troubleshooting/troubleshooting-apps.html), at the Accessing the Warden Container part which instructs you how to attach to a container.

Also we were interested how you deployed the postgresql database into a Warden container? Did you deploy it like you would deploy typical Cloud Foundry apps?

Otherwise we currently do not know of any issues with wsh process.

Thanks,
@swetharepakula
RuntimeOG Team

**Comment by ScarletTanager** [comment]
Hi @elianka ,

We are closing the issue at this time.  If you encounter it again, you may reopen the issue or create a new one.

Thanks,

@ScarletTanager & @DanLavine 
CF RuntimeOG Team
